// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest    = require("bs-jest/lib/js/src/jest.js");
var Nock    = require("nock");
var Curry   = require("bs-platform/lib/js/curry.js");
var Refetch = require("../src/Refetch.js");

require('isomorphic-fetch')
;

Nock.disableNetConnect();

describe("get", (function () {
        var scope = Nock("http://example.com");
        afterAll((function () {
                scope.restore();
                return /* () */0;
              }));
        return Jest.testAsync("get", (function (done_) {
                      scope.post("/").reply(200, {
                            foo: 42
                          });
                      Refetch.post(/* None */0, "http://example.com", "test").then((function () {
                              return Promise.resolve(Curry._1(done_, Jest.Expect[/* toBe */2](/* true */1)(Jest.Expect[/* expect */0](+scope.isDone()))));
                            }));
                      return /* () */0;
                    }));
      }));

/*  Not a pure module */
