// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Js_dict    = require("bs-platform/lib/js/js_dict.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function _encode(headers) {
  return Js_dict.fromList(List.map((function (param) {
                    if (typeof param === "number") {
                      return Pervasives.failwith("TODO");
                    } else {
                      switch (param.tag | 0) {
                        case 21 : 
                            return /* tuple */[
                                    "Content-Type",
                                    param[0]
                                  ];
                        case 46 : 
                            return /* tuple */[
                                    param[0],
                                    param[1]
                                  ];
                        default:
                          return Pervasives.failwith("TODO");
                      }
                    }
                  }), headers));
}

var Cookie = 0;

var Mime = 0;

exports.Cookie  = Cookie;
exports.Mime    = Mime;
exports._encode = _encode;
/* Js_dict Not a pure module */
