// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fetch   = require("bs-fetch/lib/js/src/Fetch.js");
var Rebase  = require("reason-rebase/lib/js/src/rebase.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

var Body = /* module */[];

function _encode(headers) {
  return Js_dict.fromList(Rebase.List[/* map */2]((function (param) {
                    if (param.tag) {
                      return /* tuple */[
                              param[0],
                              param[1]
                            ];
                    } else {
                      return /* tuple */[
                              "Content-Type",
                              param[0]
                            ];
                    }
                  }), headers));
}

var Headers = /* module */[/* _encode */_encode];

function _encodeMethod(param) {
  if (typeof param === "number") {
    if (param >= 357830602) {
      if (param !== 492530731) {
        if (param >= 891112544) {
          if (param >= 994393768) {
            return /* Patch */8;
          } else {
            return /* Post */2;
          }
        } else if (param >= 801894688) {
          return /* Head */1;
        } else {
          return /* Connect */5;
        }
      } else {
        return /* Delete */4;
      }
    } else if (param >= 3997359) {
      if (param >= 336447077) {
        return /* Trace */7;
      } else {
        return /* Put */3;
      }
    } else if (param >= 3546230) {
      return /* Get */0;
    } else {
      return /* Options */6;
    }
  } else {
    return /* Other */[param[1]];
  }
}

function _request(method_, body, headers) {
  return Fetch.RequestInit[/* make */0](Rebase.Option[/* map */2](_encodeMethod, method_), Rebase.Option[/* map */2](_encode, headers), body, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* () */0);
}

function request(method_, body, headers, url) {
  return fetch(url, _request(method_, body, headers));
}

function get(headers, url) {
  return request(/* Some */[/* GET */3546230], /* None */0, headers, url);
}

function post(headers, url, body) {
  return request(/* Some */[/* POST */891112544], /* Some */[body], headers, url);
}

exports.Body          = Body;
exports.Headers       = Headers;
exports._encodeMethod = _encodeMethod;
exports._request      = _request;
exports.request       = request;
exports.get           = get;
exports.post          = post;
/* Js_dict Not a pure module */
