// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Refetch__Request  = require("./Refetch__Request.js");
var Refetch__Response = require("./Refetch__Response.js");

function fetch$1(url, request) {
  return fetch(url, Refetch__Request._toRequestInit(request)).then((function (res) {
                return Promise.resolve(Refetch__Response._make(res));
              }));
}

function get(url) {
  return fetch$1(url, Refetch__Request.make(/* GET */3546230));
}

function post(url, body) {
  return fetch$1(url, Refetch__Request.body(body, Refetch__Request.make(/* POST */891112544)));
}

var Body = 0;

var Headers = 0;

var Response = 0;

var Request = 0;

var request = Refetch__Request.make;

exports.Body     = Body;
exports.Headers  = Headers;
exports.Response = Response;
exports.Request  = Request;
exports.request  = request;
exports.fetch    = fetch$1;
exports.get      = get;
exports.post     = post;
/* Refetch__Request Not a pure module */
