// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fetch            = require("bs-fetch/lib/js/src/Fetch.js");
var Refetch__Headers = require("./Refetch__Headers.js");

function make(method_) {
  return /* record */[
          /* method */method_,
          /* queryParams : [] */0,
          /* headers : [] */0,
          /* body : None */0
        ];
}

function header(header$1, request) {
  return /* record */[
          /* method */request[/* method */0],
          /* queryParams */request[/* queryParams */1],
          /* headers : :: */[
            header$1,
            request[/* headers */2]
          ],
          /* body */request[/* body */3]
        ];
}

function body(body$1, request) {
  return /* record */[
          /* method */request[/* method */0],
          /* queryParams */request[/* queryParams */1],
          /* headers */request[/* headers */2],
          /* body : Some */[body$1[1]]
        ];
}

function _encodeMethod(param) {
  if (typeof param === "number") {
    if (param >= 357830602) {
      if (param !== 492530731) {
        if (param >= 891112544) {
          if (param >= 994393768) {
            return /* Patch */8;
          } else {
            return /* Post */2;
          }
        } else if (param >= 801894688) {
          return /* Head */1;
        } else {
          return /* Connect */5;
        }
      } else {
        return /* Delete */4;
      }
    } else if (param >= 3997359) {
      if (param >= 336447077) {
        return /* Trace */7;
      } else {
        return /* Put */3;
      }
    } else if (param >= 3546230) {
      return /* Get */0;
    } else {
      return /* Options */6;
    }
  } else {
    return /* Other */[param[1]];
  }
}

function _toRequestInit(request) {
  return Fetch.RequestInit[/* make */0](/* Some */[_encodeMethod(request[/* method */0])], /* Some */[Refetch__Headers._encode(request[/* headers */2])], request[/* body */3], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* () */0);
}

var Body = 0;

var Headers = 0;

exports.Body           = Body;
exports.Headers        = Headers;
exports.make           = make;
exports.header         = header;
exports.body           = body;
exports._encodeMethod  = _encodeMethod;
exports._toRequestInit = _toRequestInit;
/* Refetch__Headers Not a pure module */
