// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block      = require("bs-platform/lib/js/block.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function _make(res) {
  var n = res.status;
  if (n >= 200 && n <= 299) {
    return /* Ok */Block.__(0, [res]);
  } else if (n >= 400 && n <= 599) {
    return /* Error */Block.__(1, [res]);
  } else {
    return Pervasives.failwith("TODO: Unknown status");
  }
}

function text(response) {
  return response.text();
}

var Body = 0;

var Headers = 0;

var StatusCode = 0;

exports.Body       = Body;
exports.Headers    = Headers;
exports.StatusCode = StatusCode;
exports._make      = _make;
exports.text       = text;
/* No side effect */
