// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


var json = "application/json";

var json_utf8 = "application/json; charset=utf-8";

exports.json      = json;
exports.json_utf8 = json_utf8;
/* No side effect */
