// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Js_dict    = require("bs-platform/lib/js/js_dict.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function _encode(headers) {
  return Js_dict.fromList(List.map((function (param) {
                    if (typeof param === "number") {
                      return Pervasives.failwith("TODO");
                    } else {
                      var variant = param[0];
                      if (variant !== 4099528) {
                        if (variant !== 246273139) {
                          if (variant !== 1022564063) {
                            return Pervasives.failwith("TODO");
                          } else {
                            return /* tuple */[
                                    "Content-Length",
                                    Pervasives.string_of_int(param[1])
                                  ];
                          }
                        } else {
                          return /* tuple */[
                                  "Content-Type",
                                  param[1]
                                ];
                        }
                      } else {
                        var match = param[1];
                        return /* tuple */[
                                match[0],
                                match[1]
                              ];
                      }
                    }
                  }), headers));
}

var Cookie = 0;

var Mime = 0;

exports.Cookie  = Cookie;
exports.Mime    = Mime;
exports._encode = _encode;
/* Js_dict Not a pure module */
