// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


var form = "application/x-www-form-urlencoded";

var json = "application/json";

var json_utf8 = "application/json; charset=utf-8";

var multipart = "multipart/form-data";

exports.form      = form;
exports.json      = json;
exports.json_utf8 = json_utf8;
exports.multipart = multipart;
/* No side effect */
