// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


var application_json = "application/json";

var application_json_utf8 = "application/json; charset=utf-8";

exports.application_json      = application_json;
exports.application_json_utf8 = application_json_utf8;
/* No side effect */
