// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Refetch__StatusCode = require("./Refetch__StatusCode.js");

function status(response) {
  return Refetch__StatusCode.fromInt(response.status);
}

function ok(prim) {
  return +prim.ok;
}

function json(prim) {
  return prim.json();
}

function text(prim) {
  return prim.text();
}

var StatusCode = 0;

var Headers = 0;

exports.StatusCode = StatusCode;
exports.Headers    = Headers;
exports.status     = status;
exports.ok         = ok;
exports.json       = json;
exports.text       = text;
/* No side effect */
