// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Refetch           = require("../src/Refetch.js");
var Refetch__Response = require("../src/Refetch__Response.js");

require('isomorphic-fetch')
;

Refetch.get("http://httpbin.org/get").then((function (param) {
          if (param.tag) {
            return Promise.resolve("oops!");
          } else {
            return Refetch__Response.text(param[0]);
          }
        })).then((function (text) {
        return Promise.resolve((console.log(text), /* () */0));
      }));

/*  Not a pure module */
