// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Refetch = require("../src/Refetch.js");

require('isomorphic-fetch')
;

Refetch.get(/* None */0, "http://httpbin.org/get").then((function (prim) {
          return prim.text();
        })).then((function (text) {
        return Promise.resolve((console.log(text), /* () */0));
      }));

/*  Not a pure module */
