// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array           = require("bs-platform/lib/js/array.js");
var Resync            = require("../src/Resync.js");
var Refetch           = require("../src/Refetch.js");
var Json_decode       = require("bs-json/lib/js/src/Json_decode.js");
var Refetch__Response = require("../src/Refetch__Response.js");

require('isomorphic-fetch')
;

function names(text) {
  return Json_decode.array((function (param) {
                return Json_decode.field("name", Json_decode.string, param);
              }), JSON.parse(text));
}

function printGithubRepos() {
  return Resync.Future[/* whenResolved */7]((function (text) {
                return $$Array.iter((function (prim) {
                              console.log(prim);
                              return /* () */0;
                            }), names(text));
              }), Resync.Future[/* flatMap */9]((function (param) {
                    if (param.tag) {
                      return Resync.Future[/* from */3]("oops!");
                    } else {
                      return Refetch__Response.text(param[0]);
                    }
                  }), Refetch.get("https://api.github.com/users/reasonml-community/repos")));
}

printGithubRepos(/* () */0);

exports.names            = names;
exports.printGithubRepos = printGithubRepos;
/*  Not a pure module */
