// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block   = require("bs-platform/lib/js/block.js");
var Refetch = require("../src/Refetch.js");

require('isomorphic-fetch')
;

function get() {
  Refetch.post(/* Some */[/* :: */[
              /* ContentType */Block.__(21, ["application/x-www-form-urlencoded; charset=UTF-8"]),
              /* [] */0
            ]], "https://httpbin.org/post", "title=foobar&body=bar&userId=1").then((function (prim) {
            return prim.text();
          })).then((function (text) {
          return Promise.resolve((console.log(text), /* () */0));
        }));
  return /* () */0;
}

get(/* () */0);

exports.get = get;
/*  Not a pure module */
