// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Resync            = require("../src/Resync.js");
var Refetch           = require("../src/Refetch.js");
var Json_encode       = require("bs-json/lib/js/src/Json_encode.js");
var Refetch__Request  = require("../src/Refetch__Request.js");
var Refetch__Response = require("../src/Refetch__Response.js");

require('isomorphic-fetch')
;


  const debugHttp = require('debug-http');
  debugHttp();

;

Resync.Future[/* whenResolved */7]((function (prim) {
        console.log(prim);
        return /* () */0;
      }), Resync.Future[/* flatMap */9]((function (param) {
            if (param.tag) {
              return Resync.Future[/* from */3](param[0][/* reason */1]);
            } else {
              return Refetch__Response.text(param[1]);
            }
          }), Refetch.fetch(Refetch__Request.payload(/* `Json */[
                  826371656,
                  Json_encode.object_(/* :: */[
                        /* tuple */[
                          "foo",
                          42
                        ],
                        /* :: */[
                          /* tuple */[
                            "bar",
                            "baz"
                          ],
                          /* [] */0
                        ]
                      ])
                ], Refetch__Request.header(/* `ContentType */[
                      246273139,
                      "application/json"
                    ], Refetch__Request.param("filter", "foo=true", Refetch__Request.param("sort", "DESC", Refetch.request(/* POST */891112544, /* None */0, /* None */0, /* None */0, "http://putsreq.com/FFB540W0YeOnQjBMOKVq"))))))));

/*  Not a pure module */
