// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Resync            = require("../src/Resync.js");
var Refetch           = require("../src/Refetch.js");
var Refetch__Request  = require("../src/Refetch__Request.js");
var Refetch__Response = require("../src/Refetch__Response.js");

require('isomorphic-fetch')
;


  const debugHttp = require('debug-http');
  debugHttp();

;

Resync.Future[/* whenResolved */7]((function (text) {
        console.log(text);
        return /* () */0;
      }), Resync.Future[/* flatMap */9]((function (param) {
            if (param.tag) {
              return Resync.Future[/* from */3]("oops!");
            } else {
              return Refetch__Response.text(param[0]);
            }
          }), Refetch.get("http://httpbin.org/get")));

Resync.Future[/* whenResolved */7]((function (text) {
        console.log(text);
        return /* () */0;
      }), Resync.Future[/* flatMap */9]((function (param) {
            if (param.tag) {
              return Resync.Future[/* from */3]("oops!");
            } else {
              return Refetch__Response.text(param[0]);
            }
          }), Refetch.post("http://httpbin.org/post", /* `String */[
              -976970511,
              "datathings"
            ])));

Resync.Future[/* whenResolved */7]((function (text) {
        console.log(text);
        return /* () */0;
      }), Resync.Future[/* flatMap */9]((function (param) {
            if (param.tag) {
              return Resync.Future[/* from */3]("oops!");
            } else {
              return Refetch__Response.text(param[0]);
            }
          }), Refetch.fetch("http://httpbin.org/post", Refetch__Request.body(/* `String */[
                  -976970511,
                  "fooyah!"
                ], Refetch__Request.header(/* `ContentType */[
                      246273139,
                      "application/json"
                    ], Refetch.request(/* POST */891112544))))));

/*  Not a pure module */
